name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: 
      - completed
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: ci.yml
          workflow_conclusion: success

      - name: Publish
        env:
          StorageConnectionString: ${{ secrets.StorageConnectionString }}
        run: |
          $manifest = Get-Content "Manifest\manifest.json" | ConvertFrom-Json
          $appVersion = $manifest.Version
          $projectName = "GitHub${{ github.event.repository.name }}-preview".ToLowerInvariant()
          $storageContext = New-AzureStorageContext -ConnectionString "${{ secrets.StorageConnectionString }}"
          New-AzureStorageContainer -Name $projectName -Context $storageContext -Permission "Container" -ErrorAction Ignore | Out-Null
          "RuntimePackages", "Apps", "TestApps" | % {
            if (Test-Path "$_\*") {
              $tempFile = Join-Path ([System.IO.Path]::Gettemppath()) "$([Guid]::newguid().ToString()).zip"
              Compress-Archive -path (Get-Item $_).FullName -DestinationPath $tempFile
              Set-AzureStorageBlobContent -File $tempFile -Context $storageContext -Container $projectName -Blob "$appVersion/$_.zip".ToLowerInvariant() -Force
              Set-AzureStorageBlobContent -File $tempFile -Context $storageContext -Container $projectName -Blob "latest/$_.zip".ToLowerInvariant() -Force
              Remove-Item $tempFile -Force
            }
          }


